version: "3.8"

services:
  server:
    build: .
    user: :${DAEMON_GROUP_ID:-1420}
    environment:
      IMS_DIRECTORY: File
    volumes:
      - ./conf:/opt/ims/conf
      - ./:/srv/ims
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - mysql
    command:
      - /opt/ims/bin/ims
      - "--log-file"
      - "-"
      - "--config"
      - "/opt/ims/conf/imsd.conf"
      - server
  mysql:
    image: mariadb:10.5.24
    environment:
      MARIADB_DATABASE: ims
      MARIADB_USER: ims
      MARIADB_PASSWORD: ims
      MARIADB_ROOT_HOST: "%"
      MARIADB_ROOT_PASSWORD: ims-root
    volumes:
      - ./.docker/mysql/data/:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
