version: '3.7'

services:
  ims_server: 
    container_name: ims_server
    user: :${DAEMON_GROUP_ID:-1420}
    build:
      dockerfile: ./dev.Dockerfile
    volumes:
     - ./:/srv/ims
    ports:
     - ${IMS_SERVER_PORT:-8080}:8080
    command: "tox run -e exec"