version: "3.8"

services:
  server:
    build: .
    user: :${DAEMON_GROUP_ID:-1420}
    environment:
      IMS_DIRECTORY: File
      IMS_DIRECTORY_FILE: /opt/ims/conf/directory.yaml
      IMS_DB_HOST_NAME: mysql
      IMS_DB_DATABASE: ims
      IMS_DB_USER_NAME: ims
      IMS_DB_PASSWORD: ims
    volumes:
      - ./conf:/opt/ims/conf
      - ./:/srv/ims
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - mysql
  mysql:
    image: mariadb:10.5.17
    environment:
      MARIADB_DATABASE: ims
      MARIADB_USER: ims
      MARIADB_PASSWORD: ims
      MARIADB_ROOT_HOST: "%"
      MARIADB_ROOT_PASSWORD: ims-root
    volumes:
      - ./.docker/mysql/data/:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--password=ims-root"]
      interval: 10s
      timeout: 5s
      retries: 5
