name: Auto-merge Dependabot PRs

on: pull_request

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    name: Auto-merge

    runs-on: ubuntu-latest

    if: ${{ contains('["dependabot[bot]", "pre-commit-ci[bot]"]', github.actor) }}
    steps:
      - name: Approve the PR
        run: gh pr review --approve "${{ github.event.pull_request.html_url }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge
        run: gh pr merge --squash --auto "${{ github.event.pull_request.html_url }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
